export const entityKeyMapping: { [key: string]: string } = {
  Pod: 'pod_name',
  Cluster: 'kube_cluster_name',
  Namespace: 'kube_namespace',
  Node: 'kube_node',
  Deployment: 'kube_deployment',
  ReplicaSet: 'kube_replica_set',
  Service: 'kube_service',
  PersistentVolumeClaim: 'persistentvolumeclaim',
  PersistentVolume: 'kube_persistent_volume',
  CronJob: 'kube_cron_job',
  DaemonSet: 'kube_daemon_set',
  StatefulSet: 'kube_stateful_set',
  Role: 'kube_role',
  RoleBinding: 'kube_role_binding',
  ClusterRole: 'kube_cluster_role',
  ClusterRoleBinding: 'kube_cluster_role_binding',
  ServiceAccount: 'kube_service_account',
  Ingress: 'kube_ingress',
  Job: 'kube_job',
};
